# Generated by Django 5.0.6 on 2024-05-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "number",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name="Номер стола"),
                ),
                (
                    "table_type",
                    models.PositiveSmallIntegerField(
                        choices=[(None, "Not defined"), (1, "Billiard"), (2, "Tennis")], verbose_name="Тип стола"
                    ),
                ),
            ],
            options={
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
            },
        ),
    ]
