import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Header } from '@/shared/ui/Header';
import { Footer } from '@/shared/ui/Footer';
import '@/app/styles/index.scss';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Port Place',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
