# Generated by Django 5.0.6 on 2024-05-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.CharField(max_length=150, verbose_name="Описание")),
                ("number", models.CharField(blank=True, max_length=15, null=True, verbose_name="Номер телефона")),
                ("photo", models.ImageField(upload_to="residents/", verbose_name="Фото")),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[(0, "Заявка на рассмотрении"), (1, "Активный резидент"), (2, "Заявка отклонена")],
                        default=0,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Резидент",
                "verbose_name_plural": "Резиденты",
            },
        ),
    ]
