# Generated by Django 5.0.6 on 2024-05-26 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guest_name", models.CharField(blank=True, max_length=50, verbose_name="Имя гостя")),
                ("guest_phone", models.CharField(blank=True, max_length=20, verbose_name="Номер гостя")),
                ("start", models.DateTimeField(verbose_name="Начало")),
                ("end", models.DateTimeField(verbose_name="Конец")),
                (
                    "table",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="tables.table"),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "default_related_name": "reservations",
            },
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                check=models.Q(("start__lt", models.F("end"))), name="reservations_reservation_end_gt_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("end__isnull", True), ("start__isnull", True)),
                    models.Q(("end__isnull", False), ("start__isnull", False)),
                    _connector="OR",
                ),
                name="reservations_reservation_end_start_both_or_none",
            ),
        ),
    ]
